name: Regenerate Jira Client

on:
  schedule:
    - cron: '0 0 1 * *' # Run at the start of every month
  workflow_dispatch:    # Allow Manual Triggering

jobs:
  update-jira-client:
    name: Update Jira Client from OAS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 2
          command:  composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Generate Jira Client
        run: ./bin/jira generate

      - name: Check for changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "skip_pr=true" >> $GITHUB_ENV
          else
            echo "Changes detected."
          fi

      - name: Set Formatted Date
        id: set_date
        run: echo "formatted_date=$(date +'%B %Y')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: PAT_WORKFLOW_TOKEN
          title: "Monthly Jira Client Update [${{ steps.set_date.outputs.formatted_date }}]"
          body: "Automated update of the Jira Cloud API client based on the latest Open API Specification."
          branch: "auto-update"
          branch-suffix: "short-commit-hash"
          commit-message: "chore: Monthly Jira Client updates for ${{ steps.set_date.outputs.formatted_date }}"
          base: master
          labels: auto-update
      
